# Generated by Django 3.2.16 on 2022-10-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='toyosi-assets/images/posts/%Y/%m/%d'),
        ),
    ]
