# Generated by Django 3.2.16 on 2022-10-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20221017_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/categories/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='other_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/products/%Y/%m/%d'),
        ),
    ]
