# Generated by Django 3.2.16 on 2022-10-17 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_product_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='favorites',
            new_name='user_favorites',
        ),
        migrations.AddField(
            model_name='product',
            name='user_recent',
            field=models.ManyToManyField(blank=True, related_name='recent_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
