# Generated by Django 3.2.16 on 2022-10-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20221017_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='toyosi-assets/images/categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='toyosi-assets/images/products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='other_image',
            field=models.ImageField(blank=True, null=True, upload_to='toyosi-assets/images/products/%Y/%m/%d'),
        ),
    ]
