# Generated by Django 3.2.16 on 2022-12-05 18:39

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_number',
            field=models.CharField(default=orders.models.id_gen, editable=False, max_length=50),
        ),
    ]
