# Generated by Django 3.2.16 on 2022-12-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20221205_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
